### ISSUE TITLE
cannot upgrade vm to latest mesos + marathon

### ISSUE THREAD

**Issue by tysonnorris** [mesosphere/playa-mesos#14]
Trying to update to latest mesos + marathon versions using:
vagrant up
vagrant provision

I always get errors (output below) related to /etc/bash_completion.d/docker.io - is there a different box that may be better, or some other way to upgrade? Currently box is http://downloads.mesosphere.io/playa-mesos/playa_mesos_ubuntu_14.04.box

==> default: Setting up libsvn1:amd64 (1.8.8-1ubuntu3.1) ...
==> default: Setting up docker.io (1.0.1~dfsg1-0ubuntu1~ubuntu0.14.04.1) ...
==> default: Setting up marathon (0.7.5-1.0) ...
==> default: 
==> default: Configuration file '/etc/bash_completion.d/docker.io'
==> default:  ==> Modified (by you or by a script) since installation.
==> default:  ==> Package distributor has shipped an updated version.
==> default:    What would you like to do about it ?  Your options are:
==> default:     Y or I  : install the package maintainer's version
==> default:     N or O  : keep your currently-installed version
==> default:       D     : show the differences between the versions
==> default:       Z     : start a shell to examine the situation
==> default:  The default action is to keep your current version.
==> default: *** docker.io (Y/I/N/O/D/Z) [default=N] ? 
==> default: Configuration file '/etc/bash_completion.d/docker.io'
==> default:  ==> Modified (by you or by a script) since installation.
==> default:  ==> Package distributor has shipped an updated version.
==> default:    What would you like to do about it ?  Your options are:
==> default:     Y or I  : install the package maintainer's version
==> default:     N or O  : keep your currently-installed version
==> default:       D     : show the differences between the versions
==> default:       Z     : start a shell to examine the situation
==> default:  The default action is to keep your current version.
==> default: *** docker.io (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package docker.io (--configure):
==> default:  EOF on stdin at conffile prompt
==> default: Setting up mesos (0.21.0-1.0.ubuntu1404) ...
==> default: Processing triggers for libc-bin (2.19-0ubuntu6) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Errors were encountered while processing:
==> default:  docker.io
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: A package failed to install.  Trying to recover:
==> default: Setting up docker.io (1.0.1~dfsg1-0ubuntu1~ubuntu0.14.04.1) ...
==> default: 
==> default: Configuration file '/etc/bash_completion.d/docker.io'
==> default:  ==> Modified (by you or by a script) since installation.
==> default:  ==> Package distributor has shipped an updated version.
==> default:    What would you like to do about it ?  Your options are:
==> default:     Y or I  : install the package maintainer's version
==> default:     N or O  : keep your currently-installed version
==> default:       D     : show the differences between the versions
==> default:       Z     : start a shell to examine the situation
==> default:  The default action is to keep your current version.
==> default: *** docker.io (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package docker.io (--configure):
==> default:  EOF on stdin at conffile prompt
==> default: Errors were encountered while processing:
==> default:  docker.io
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Reading extended state information...
==> default: Initializing package states...
==> default: Writing extended state information...
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by ssk2** [comment]
A workaround is simply to `vagrant ssh` into the box and then run `sudo apt-get upgrade`. This will update Mesos and Marathon packages to the latest.
