### ISSUE TITLE
Would it be dificult to add more hosts automatically?

### ISSUE THREAD

**Issue by mihai-satmarean** [mesosphere/playa-mesos#15]
Hi, due to the way the Vagrant is used, it is a bit difficult for me to  imagine how more hosts would be added, I have never used this type of configuration.
Can anyone help or point out how to do it in order to have a multi master, multi slave environment?
Thank you!

**Comment by ssk2** [comment]
Please checkout the Advanced Mesos Course for instructions on how to set up a multi-node Vagrant cluster: https://open.mesosphere.com/intro-course/ex10.html
