### ISSUE TITLE
Permission Denied when trying to enable Docker

### ISSUE THREAD

**Issue by lordofthejars** [mesosphere/playa-mesos#21]
Hi I have just installed today the playa-mesos on my computer and it works pretty well, but when I try to enable docker by using `echo 'docker,mesos' > /etc/mesos-slave/containerizers`, it throws me a Permission denied exception. And the same happens if I use the `sudo` command. Any idea of what I can do to enable Docker in this case?

Thank you so much.

**Comment by michaeljin** [comment]
Hello, `sudo` doesn't play well with shell redirection. You have too options: 1) Switch to the root user with `su` and run the command or 2) Run `echo 'docker,mesos' > sudo dd of=/etc/mesos-slave/containerizers`
