### ISSUE TITLE
How to Install Ruby & Bundler on Slave?

### ISSUE THREAD

**Issue by hhff** [mesosphere/playa-mesos#22]
Hiya!!  Vetting Mesosphere for an upcoming project.  Attempting to install Ruby 2.0 & Bundler on the 1x Slave that the Vagrant box sets up.

```
servers=(10.141.141.10); for s in "${servers[@]}"; do ssh -l ubuntu $s 'sudo apt-get -y install ruby2.0 && sudo gem install bundler' ; done
```

The slave is prompting me for a password?

**Comment by ssk2** [comment]
Hi @hhff, sorry for the delay in responding to you. Did you figure this out?

You'll probably want to use `vagrant ssh` to get into the playa-mesos slave, or you'll have to do that first and add a public key to the `ubuntu` account.

**Comment by hhff** [comment]
Thanks @ssk2 - ended up going with Deis.  Doesn't seem like the docs / community are here yet - and that doesn't bode well for a new client project.

Love the vision and excited to use this in the future when it all matures a bit :smile:

**Comment by ssk2** [comment]
No worries! Please give DCOS a try when it comes out in the next couple of months!
