### ISSUE TITLE
bump ubuntu iso version

### ISSUE THREAD

**Issue by spacejam** [mesosphere/playa-mesos#25]
s/`ubuntu-14.04-server-amd64.iso`/`ubuntu-14.04.2-server-amd64.iso`/g
@joerg84

**Comment by spacejam** [comment]
s/`ababb88a492e08759fddcf4f05e5ccc58ec9d47fa37550d63931d0a5fa4f7388`/`8acd2f56bfcba2f7ac74a7e4a5e565ce68c024c38525c0285573e41c86ae90c0`/g

**Comment by ssk2** [comment]
@spacejam - can you submit a pull request for this change?
