### ISSUE TITLE
Upgrade to Marathon 0.8.2

### ISSUE THREAD

**Issue by kolloch** [mesosphere/playa-mesos#26]
The Marathon is pretty out-dated.

**Comment by ssk2** [comment]
+1. Think we need to revisit this project entirely though - looks like it's still installing `deimos` too. https://github.com/mesosphere/playa-mesos/blob/master/lib/scripts/common/mesosflexinstall#L69

**Comment by ssk2** [comment]
Done! I've updated the box, so if you do a fresh clone of this project and `vagrant up`, you should get the latest box...

**Comment by ssk2** [comment]
Tested and this works for me now! Go play.
