### ISSUE TITLE
bin/test and lib/assert.sh/assert.sh needed a dos2unix conversion to work

### ISSUE THREAD

**Issue by bonsors** [mesosphere/playa-mesos#31]
Environment 
Windows 7
cygwin
VirtualBox version : 4.3
Vagrant version : 1.7

Attempt to run Quick start step 4 fails
bin/test
bin/test: line 2: $'\r': command not found
bin/test: line 5: $'\r': command not found
: No such file or directory/d/VAGRANTS/playa-mesos
bin/test: line 8: $'\r': command not found
bin/test: line 12: $'\r': command not found
bin/test: line 14: assert_raises: command not found
bin/test: line 15: assert_raises: command not found
bin/test: line 16: assert_raises: command not found
bin/test: line 17: assert_raises: command not found
bin/test: line 18: $'\r': command not found
bin/test: line 20: assert: command not found
bin/test: line 21: assert: command not found
bin/test: line 22: $'\r': command not found
VirtualBox version discovered: 4.3
bin/test: line 26: assert: command not found
bin/test: line 27: $'\r': command not found
Vagrant version discovered: 1.7
bin/test: line 31: assert: command not found
bin/test: line 32: $'\r': command not found

After dos2unix of test and assert.sh
 bin/test
VirtualBox version discovered: 4.3
Vagrant version discovered: 1.7
all 8 playa-mesos tests passed in 0.816s.

**Comment by ssk2** [comment]
Thanks for the bug report @bonsors - we're working on a new sandboxed environment for testing Mesos clusters which should be more Windows friendly!
