### ISSUE TITLE
Mesos Master Needs IP other than 127.0.0.1 for remote access

### ISSUE THREAD

**Issue by gabrielhartmann** [mesosphere/playa-mesos#32]
Attempting to run a scheduler against this VM doesn't work because master is identified as being on 127.0.0.1.

Logs indicate this:
    New master master@127.0.1.1:5050 detected
when instead it should be on something like 
    New master master@10.141.141.10:5050 detected

For example, the GO examples don't work using this VM. See:
https://github.com/mesosphere/mesos-go

**Comment by ssk2** [comment]
A workaround is to set one of the config properties for the package and then restart the mesos-master. 

See: https://open.mesosphere.com/reference/mesos-master/
```
A file named the same name as the flag may be placed in the /etc/mesos-master directory. So a /etc/mesos-master/hostname file containing the value of 10.141.141.10 is like running the master with the option --hostname=10.141.141.10
```
