### ISSUE TITLE
Is there a way to add a remote mesos slave

### ISSUE THREAD

**Issue by ZeroGraviti** [mesosphere/playa-mesos#34]
I am trying to figure out how to add a remote mesos slave into the vagrant mesos-master and mesos-marathon provided as part of this git project. The remote mesos slave is in a docker container and one of the command line options to start that remote docker container has the zk url applicable for this mesos master ie 10.141.141.10 @ port 2181. 
I dont see the docker mesos-slave in the vagrant mesos-master. Can someone help me out if I have missed something or if this is not possible even ?

**Comment by ssk2** [comment]
When you say remote, is this running on the same machine? AFAIK that IP address will only be reachable from the machine on which the Vagrant machine is running.

Note also that for Mesos slaves to register against the master successfully, the master must be able to route back to the slave node to confirm registration. You might want to check that whatever IP address the Mesos slave is bound to can be reached from within the Vagrant machine.

**Comment by ZeroGraviti** [comment]
yes the mesos slave ip can be reached (pinged) from within the vagrant mesos-master and vice-versa. I have also been able to successfully telnet on 2181 from the mesos-slave (docker) to the mesos-master (vagrant).
