### ISSUE TITLE
Looks like docker cannot pull images from the docker public registry

### ISSUE THREAD

**Issue by ZeroGraviti** [mesosphere/playa-mesos#36]
If this is true, what is the fix ?

**Comment by ssk2** [comment]
Works for me. Is the image public?

**Comment by ZeroGraviti** [comment]
Yes, generic images for nginx and redis.

**Comment by ZeroGraviti** [comment]
Let me see if this is something to do with my recent password docker hub changes.... wait...

**Comment by ZeroGraviti** [comment]
Looks like that fixed it. Closing this issue. BTW is there going to be support for an updated version of docker in this project ?

**Comment by ssk2** [comment]
We're actually in the process of replacing this entirely - so we won't be updating this specific project but will be replacing it with a new project that has the latest components of Mesos, Marathon and Docker.
