### ISSUE TITLE
Multi Node Vagrant would be great

### ISSUE THREAD

**Issue by Arwany** [mesosphere/playa-mesos#39]
Hi,

It would be great if there could be a settings to setup mesos with marathon and haproxy on multiple nodes, say like 1 master, 2 slaves, and separate machine for marathon framework.

Thanks

**Comment by ssk2** [comment]
Hey @Arwany, check out the Advanced Mesos Course here: https://open.mesosphere.com/advanced-course/starting-four-nodes/, it has instructions on how to do this.

We're in the process of deprecating this project and will soon replace it with a new Vagrant image. We'll take your feedback into consideration and see if it's possible to release that with multiple node support!

Cheers!

**Comment by Arwany** [comment]
Thanks for the answer.

I am working already with this one (https://github.com/everpeace/vagrant-mesos), it works but I need to hack into the slaves & masters and install the haprox, so I would give more feedback on what could be included on the vagrant up directly:

- haproxy for load balancing.
- mesos-dns this would save us a lot of efforts, and for the starters could save them some search.
- Options for other service discovery (like Consul) or something (if needed).

Again thanks for the answer.
